version: '3'

services:
  fluentd:
    build:
      context: .
    networks:
      - shared-network
    volumes:
      - C:\Users\VASU03\Documents\ekf\efk-local\fluentd:/app/fluentd
    command: /bin/sh -c "python3 /app/dummy_logs.py & fluentd -c /app/fluentd/fluentd.conf"
  
    ports:
      - "24224:24224"
      - "24224:24224/udp"

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.10.1
    networks:
      - shared-network
    ports:
      - "9200:9200"
    environment:
      ES_JAVA_OPTS: "-Xms1g -Xmx1g"
      discovery.type: "single-node"
      node.store.allow_mmap: "false"
      
  kibana:
    image: docker.elastic.co/kibana/kibana:7.10.1
    networks:
      - shared-network
    ports:
      - "5601:5601"
    depends_on:
      - elasticsearch

networks:
  shared-network:
    driver: bridge
